version: '3.8'

services:
  gazebo_sim:
    image: kaberov_robot:latest
    build:
      context: ./code
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - /tmp/.x11-unix:/tmp/.x11-unix:ro
      - ~/.Xauthority:/tmp/.Xauthority:ro
      - ./config.json:/src/config.json:rw
    devices:
      - /dev/dri:/dev/dri
    ipc: host
